### ISSUE TITLE
Kotlin support

### ISSUE THREAD

**Issue by hkokocin** [google/truth#404] opened 2018-01-24 20:12 UTC
Are there any plans to add an extension for usage in Kotlin? There would be a lot of potential. I'm still quite new to Truth so I hope I did not miss sth but for example I currently use 

```
assertThat(mapMarkers.any { it.data == myData }).isTrue()
```

Instead it would be great to have

```
assertThat(mapMarkers).containsAny{ it.data == myData }
```

Quite interesting for collections would also be `all` and `none`. And I think there will be more examples like that which would be very nice to have.

**Comment by JakeWharton** [comment] 2018-01-24 20:32
One could argue this has nothing to do with Kotlin as such a method could be beneficial to Java 8 consumers as well.

But since `IterableSubject` no longer carries a type parameter (#192), I don't see a way to achieve this with an instance method:
```java
// No "T" to use, Object and ? aren't usable.
public void containsAny(Predicate<T> predicate) { /* .. */ }
```
Nor is there a way to do it yourself with a Kotlin extension method:
```kotlin
// Again no "T" to use and Any or * aren't usable.
fun IterableSubject.containsAny(predicate: (T) -> Boolean) = /* .. */
```

The best you can do with Kotlin, though, is hanging the extension off of the iterable directly:
```kotlin
fun <T> Iterable<T>.assertContainsAny(predicate: (T) -> Boolean) {
    assertTrue(this.any(predicate))
    // TODO better failure message
}
```
yielding
```kotlin
mapMarkers.assertContainsAny { it.data == myData }
```
The absence of a type parameter limits the ability to create these style helpers directly on the subject.

All that being said, there are some _really_ handy Kotlin extensions that I use with Truth. My favorite is:
```kotlin
inline fun <reified T> assertThrows(block: () -> Unit): ThrowableSubject {
  try {
    block()
  } catch (e: Throwable) {
    if (e is T) {
      return assertThat(e)
    } else {
      throw e
    }
  }
  throw AssertionError("Expected ${T::class.simpleName}")
}
```
([source](https://github.com/square/kotlinpoet/blob/87f4f1b0cb34c628b4f16c29bb26a5ccdb3aef32/src/test/java/com/squareup/kotlinpoet/assertions.kt#L21-L32))

which lets you do:
```kotlin
assertThrows<IllegalArgumentException> {
  FunSpec.builder("foo")
      .addTypeVariable(TypeVariableName("T").reified())
      .build()
}.hasMessageThat().isEqualTo("only type parameters of inline functions can be reified!")
```
([source](https://github.com/square/kotlinpoet/blob/87f4f1b0cb34c628b4f16c29bb26a5ccdb3aef32/src/test/java/com/squareup/kotlinpoet/FunSpecTest.kt#L315-L319))

**Comment by JakeWharton** [comment] 2018-01-24 20:38
I suppose the Java instance method and the Kotlin extension function could define their own `T`, but that means you can do bad things like
```kotlin
assertThat(listOf("Hello", "World")).containsAny<Integer> { it % 2 == 0 }
```
which is an unnecessary foot gun.

**Comment by PhilippWendler** [comment] 2018-01-25 06:26
This looks like a duplicate of #206?

**Comment by hkokocin** [comment] 2018-01-25 08:35
@JakeWharton Of course you are totally right that it would be a treat to have `containsAny`, `containsNone`, `containsAll` as regular matchers. I was a bit caught in Kotlin APIs. The intent of this issue was to have these matchers supported natively and maybe its worth considering? Thanks a lot for your insights on how to use custom extension functions though.

@PhilippWendler The issue you linked is in fact part of what I want to archieve. Thanks for the hint.

**Comment by ultraon** [comment] 2018-12-15 21:45
You can check this great assertion library for Kotlin https://github.com/robstoll/atrium

**Comment by cpovirk** [comment] 2019-05-14 14:08
To the degree that this bug is about `Predicate`-accepting assertions, we're unlikely to implement it. See https://github.com/google/truth/issues/206, https://github.com/google/truth/issues/311, and https://github.com/google/truth/issues/435.

I'm going to leave the other Kotlin bug, https://github.com/google/truth/issues/435, open, as it addresses another concern about extension methods. I'll retitle it accordingly.

**Closed by cpovirk** 2019-05-14 14:08 UTC
